//特殊字符要显示的内容，即正文中应该是什么
export const specialCharacters = {
  '\u0000': '－', '\u0001': '?', '\u0002': '×', '\u0003': '?',
  '\u0004': '?', '\u0005': '?', '\u0006': '?', '\u0007': '?',
  '\u0008': '?', '\u000f': '●',
};
//特殊字符对应显示为unicode码
export const specialCharaDisplay = {
  '\u0000': '\\u0000', '\u0001': '\\u0001', '\u0002': '\\u0002', '\u0003': '\\u0003',
  '\u0004': '\\u0004', '\u0005': '\\u0005', '\u0006': '\\u0006', '\u0007': '\\u0007',
  '\u0008': '\\u0008'
};
export const boldFontStyle = ["AdvTT7d6ad6bc", "AdvP4ADA8D", "AdvP4AA440", "AdvP978E", "AdvP405AA6", "AdvPi3", "AdvTTecf15426.B", "AdvP418142"];
export const italicFontStyle = ["AdvP9794", 'AdvTT52d06db3.I',];
export const boldItalicFontStyle = [];
export const normalFontStyle = ["AdvP9725",];
export const fontStyleCollection = {
  boldFontStyle: boldFontStyle,
  italicFontStyle: italicFontStyle,
  boldItalicFontStyle: boldItalicFontStyle,
};


export const langCode_franVsZotero = {
  "cmn": "zh",
  "spa": "es",
  "eng": "en",
  "rus": "ru",
  "arb": "ar",
  "ben": "",
  "hin": "hi",
  "por": "pt",
  "ind": "id",
  "jpn": "ja",
  "fra": "fr",
  "deu": "de",
  "jav": "",
  "kor": "ko",
  "tel": "",
  "vie": "",
  "mar": "",
  "ita": "",
  "tam": "",
  "tur": "",
  "urd": "",
  "guj": "",
  "pol": "",
  "ukr": "",
  "kan": "",
  "mai": "",
  "mal": "",
  "pes": "",
  "mya": "",
  "swh": "",
  "sun": "",
  "ron": "",
  "pan": "",
  "bho": "",
  "amh": "",
  "hau": "",
  "fuv": "",
  "hrv": "",
  "nld": "",
  "srp": "",
  "tha": "",
  "ckb": "",
  "yor": "",
  "uzn": "",
  "zlm": "",
  "ibo": "",
  "npi": "",
  "ceb": "",
  "skr": "",
  "tgl": "",
  "hun": "",
  "azj": "",
  "sin": "",
  "koi": "",
  "ell": "",
  "ces": "",
  "mag": "",
  "run": "",
  "bel": "",
  "plt": "",
  "qug": "",
  "mad": "",
  "nya": "",
  "zyb": "",
  "pbu": "",
  "kin": "",
  "zul": "",
  "bul": "",
  "swe": "",
  "lin": "",
  "som": "",
  "hms": "",
  "hnj": "",
  "ilo": "",
  "kaz": "",
  "uig": "",
  "hat": "",
  "khm": "",
  "prs": "",
  "hil": "",
  "sna": "",
  "tat": "",
  "xho": "",
  "hye": "",
  "min": "",
  "afr": "",
  "lua": "",
  "sat": "",
  "bod": "",
  "tir": "",
  "fin": "",
  "slk": "",
  "tuk": "",
  "dan": "",
  "nob": "",
  "suk": "",
  "als": "",
  "sag": "",
  "nno": "",
  "heb": "",
  "mos": "",
  "tgk": "",
  "cat": "",
  "sot": "",
  "kat": "",
  "bcl": "",
  "glg": "",
  "lao": "",
  "lit": "",
  "umb": "",
  "tsn": "",
  "vec": "",
  "nso": "",
  "ban": "",
  "bug": "",
  "knc": "",
  "kng": "",
  "ibb": "",
  "lug": "",
  "ace": "",
  "bam": "",
  "tzm": "",
  "ydd": "",
  "kmb": "",
  "lun": "",
  "shn": "",
  "war": "",
  "dyu": "",
  "wol": "",
  "kir": "",
  "nds": "",
  "fuf": "",
  "mkd": "",
  "vmw": "",
  "zgh": "",
  "ewe": "",
  "khk": "",
  "slv": "",
  "ayr": "",
  "bem": "",
  "emk": "",
  "bci": "",
  "bum": "",
  "epo": "",
  "pam": "",
  "tiv": "",
  "tpi": "",
  "ven": "",
  "ssw": "",
  "nyn": "",
  "kbd": "",
  "iii": "",
  "yao": "",
  "lvs": "",
  "quz": "",
  "src": "",
  "rup": "",
  "sco": "",
  "tso": "",
  "men": "",
  "fon": "",
  "nhn": "",
  "dip": "",
  "kde": "",
  "kbp": "",
  "tem": "",
  "toi": "",
  "ekk": "",
  "snk": "",
  "cjk": "",
  "ada": "",
  "aii": "",
  "quy": "",
  "rmn": "",
  "bin": "",
  "gaa": "",
  "ndo": "",
};