//特殊字符要显示的内容，即正文中应该是什么
export const specialCharacters = {
  '\u0000': '－', '\u0001': '?', '\u0002': '×', '\u0003': '?',
  '\u0004': '?', '\u0005': '?', '\u0006': '?', '\u0007': '?',
  '\u0008': '?', '\u000f': '●',
};
//特殊字符对应显示为unicode码
export const specialCharaDisplay = {
  '\u0000': '\\u0000', '\u0001': '\\u0001', '\u0002': '\\u0002', '\u0003': '\\u0003',
  '\u0004': '\\u0004', '\u0005': '\\u0005', '\u0006': '\\u0006', '\u0007': '\\u0007',
  '\u0008': '\\u0008'
};
export const pdfCharasReplace = {
  "¼": "=",
  '\\u0000': '－',
  '\\u0002': '×',
  '\\u0003': '－',
  '\\u0004': '*',
  '\\u000f': '●',
};
export const boldFontStyle = ["AdvTT7d6ad6bc", "AdvP4ADA8D", "AdvP4AA440", "AdvP978E", "AdvP405AA6", "AdvPi3", "AdvTTecf15426.B", "AdvP418142"];
export const italicFontStyle = ["AdvP9794", 'AdvTT52d06db3.I',];
export const boldItalicFontStyle = [];
export const normalFontStyle = ["AdvP9725",];
export const fontStyleCollection = {
  boldFontStyle: boldFontStyle,
  italicFontStyle: italicFontStyle,
  boldItalicFontStyle: boldItalicFontStyle,
};


export const langCode_francVsZotero = {
  "cmn": "zh",
  "spa": "es",
  "eng": "en",
  "rus": "ru",
  "arb": "ar",
  "ben": "bd",
  "hin": "hi",
  "por": "pt",
  "ind": "id",
  "jpn": "ja",
  "fra": "fr",
  "deu": "de",
  "jav": "",
  "kor": "ko",
  "tel": "",
  "vie": "",
  "mar": "",
  "ita": "",
  "tam": "",
  "tur": "",
  "urd": "",
  "guj": "",
  "pol": "",
  "ukr": "",
  "kan": "",
  "mai": "",
  "mal": "",
  "pes": "fa",
  "mya": "",
  "swh": "",
  "sun": "",
  "ron": "",
  "pan": "",
  "bho": "",
  "amh": "",
  "hau": "",
  "fuv": "",
  "bos": "",
  "hrv": "",
  "nld": "",
  "srp": "",
  "tha": "",
  "ckb": "",
  "yor": "",
  "uzn": "",
  "zlm": "",
  "ibo": "",
  "npi": "",
  "ceb": "",
  "skr": "",
  "tgl": "",
  "hun": "",
  "azj": "",
  "sin": "",
  "koi": "",
  "ell": "el",
  "ces": "cs",
  "mag": "",
  "run": "",
  "bel": "",
  "plt": "",
  "qug": "",
  "mad": "",
  "nya": "",
  "zyb": "",
  "pbu": "",
  "kin": "",
  "zul": "",
  "bul": "bg",
  "swe": "",
  "lin": "",
  "som": "",
  "hms": "",
  "hnj": "",
  "ilo": "",
  "kaz": "",
};